from Motoman import *


robot = RobotPost('Motomantest', 'Motoman robot', 6)

robot.ProgStart("Program")
robot.RunMessage("Program generated by RoboDK", True)
robot.setFrame(Pose([807.766544, -963.699898, 41.478944, 0, 0, 0]), None, 0)
robot.setTool(Pose([62.5, -108.253175, 100, -60, 90, 0]), None, 0)
robot.MoveJ(Pose([200, 200, 500, 180, 0, 180]), [-46.18419, -6.77518, -20.54925, 71.38674, 49.58727, -302.54752] )
robot.MoveL(Pose([200, 250, 348.734575, 180, 0, -150]), [-41.62707, -8.89064, -30.01809, 60.62329, 49.66749, -258.98418] )
# robot.MoveL(Pose([200, 200, 262.132034, 180, 0, -150]), [-43.73892, -3.91728, -35.77935, 58.57566, 54.11615, -253.81122] )
robot.ProgFinish("Program")
robot.ProgSave(".","OUTPUT",True)

print(robot.PROG_FILES)
robot.PROG_FILES.append("BACK34IN.JBI")
robot.ProgSendRobot('192.168.1.31','JOB',"ftp","")


# for line in lines:
#     newline=line.replace('\n','$').replace('$','\r\n').replace("END","END\r").replace("POSTYPE BASE","POSTYPE USER").replace("FRAME BASE","FRAME USER")
#     if("POSTYPE" in line):
#         file10.write("///USER 1\r\n")
#     file10.write(newline)