from robodk import *
import sys

from Motoman_Cartesian import RobotPost, p

def main():
    r = RobotPost(r"""Motoman""",r"""Motoman MA2010""",6, axes_type=['R','R','R','R','R','R'], ip_com=r"""127.0.0.1""", api_port=20500, prog_ptr=1976622395408, robot_ptr=1976635615216, pulses_x_deg=[1341.4, 1341.4, 1341.4, 1000, 1000, 622])
    r.STR_VJ='VJ=10.00'
    r.ProgStart(r"""AAA""")
    r.RunMessage(r"""Program generated by RoboDK v5.3.2 for Motoman MA2010 on 28/10/2022 12:18:47""",True)
    r.RunMessage(r"""Using nominal kinematics.""",True)
    r.setFrame(p(0,0,0,0,0,0),-1,r"""Motoman MA2010 Base""")
    r.MoveJ(p(1232,0,860,0,0,-180),[0,0,0,0,0,0],[0,0,0])
    r.MoveJ(p(1232,0,593.478,0,0,-180),[0,-1.23097,-15.1604,0,13.9294,0],[0,0,0])
    r.MoveJ(p(903.741,0,593.478,0,0,-180),[0,-27.1205,-36.7057,0,9.58517,0],[0,0,0])
    r.ProgFinish(r"""AAA""")
    r.ProgSave(".","AAA",False)

    file=open("AAA.JBI","r")
    file_new=open("AAA2.JBI","w")
    lines=file.readlines()
    for i in range(len(lines)):
        if 'RJ' in lines[i]:
            file_new.write(lines[i][:-4]+lines[i][-1:])
        else:
            file_new.write(lines[i])

    file.close()
    file_new.close()

    r.PROG_FILES=[]
    print(r.PROG_FILES)
    r.PROG_FILES.append("AAA2.JBI")
    r.ProgSendRobot('192.168.55.1','JOB',"ftp","")

    ###Execution


if __name__ == "__main__":
    main()
